# Kafka UI - Web Dashboard for Kafka Management
# Provides cluster monitoring, topic management, consumer group tracking
# Reference: https://github.com/provectuslabs/kafka-ui

---
# Namespace - shared with Kafka
apiVersion: v1
kind: Namespace
metadata:
  name: kafka-ns
  labels:
    name: kafka-ns

---
# ConfigMap for Kafka UI configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-config
  namespace: kafka-ns
  labels:
    app: kafka-ui
    component: config
data:
  # Kafka UI environment variables
  KAFKA_CLUSTERS_0_NAME: "kafka-local"
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
  KAFKA_CLUSTERS_0_METRICS_PORT: "9092"
  
  # Optional: JMX metrics (requires Kafka broker JMX setup)
  # KAFKA_CLUSTERS_0_JMXPORT: "9999"
  
  # Optional: Kafka Connect cluster
  # KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: "kafka-connect-local"
  # KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: "kafka-connect:8083"
  
  # Optional: Schema Registry
  # KAFKA_CLUSTERS_0_SCHEMAREGISTRY: "http://schema-registry:8081"
  
  # Optional: KSQL cluster
  # KAFKA_CLUSTERS_0_KSQLDBSERVER: "http://ksql-server:8088"
  
  # UI Settings
  KAFKA_UI_BROKERS_CLUSTERIDENTIFIER: "kafka-local"
  
  # Authentication (optional - uncomment to enable)
  # AUTH_TYPE: "LOGIN_PAGE"
  # SPRING_SECURITY_USER_NAME: "admin"
  # SPRING_SECURITY_USER_PASSWORD: "admin"
  
  # Logging level
  LOGGING_LEVEL_COM_PROVECTUS: "INFO"
  LOGGING_LEVEL_ROOT: "WARN"
  
  # Dynamic cluster discovery (optional)
  KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITINGCONSUMERGROUP_ENABLED: "false"

---
# ServiceAccount for Kafka UI
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-ui
  namespace: kafka-ns
  labels:
    app: kafka-ui

---
# Role for Kafka UI (minimal RBAC)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafka-ui
  namespace: kafka-ns
  labels:
    app: kafka-ui
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]

---
# RoleBinding for Kafka UI
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-ui
  namespace: kafka-ns
  labels:
    app: kafka-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kafka-ui
subjects:
  - kind: ServiceAccount
    name: kafka-ui
    namespace: kafka-ns

---
# Deployment for Kafka UI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka-ns
  labels:
    app: kafka-ui
    component: ui
spec:
  replicas: 1                              # Scale up for high availability
  selector:
    matchLabels:
      app: kafka-ui
      component: ui
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: kafka-ui
        component: ui
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      serviceAccountName: kafka-ui
      
      # Security context
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest      # Use specific version in production
          imagePullPolicy: IfNotPresent
          
          # Security context
          securityContext:
            runAsUser: 1001
            runAsNonRoot: true
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          
          # Container port
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          
          # Environment from ConfigMap
          envFrom:
            - configMapRef:
                name: kafka-ui-config
          
          # Additional environment variables
          env:
            # JVM settings
            - name: JAVA_OPTS
              value: "-Xms256M -Xmx512M"
            
            # Server settings
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/"
          
          # Liveness probe
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          
          # Readiness probe
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          
          # Resource requests and limits
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          
          # Volume mounts (optional - for custom config)
          volumeMounts:
            - name: temp
              mountPath: /tmp
      
      # Volumes
      volumes:
        - name: temp
          emptyDir: {}
      
      # Pod termination grace period
      terminationGracePeriodSeconds: 30

---
# ClusterIP Service for Kafka UI (internal access)
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: kafka-ns
  labels:
    app: kafka-ui
    component: ui
spec:
  type: ClusterIP
  selector:
    app: kafka-ui
    component: ui
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP

---
# LoadBalancer Service for Kafka UI (external access)
# Change to NodePort or Ingress for production
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-external
  namespace: kafka-ns
  labels:
    app: kafka-ui
    component: ui
spec:
  type: LoadBalancer
  selector:
    app: kafka-ui
    component: ui
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

---
# Optional: HorizontalPodAutoscaler for Kafka UI
# Uncomment if running high-traffic environment
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: kafka-ui
#   namespace: kafka-ns
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: kafka-ui
#   minReplicas: 2
#   maxReplicas: 5
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 70
#     - type: Resource
#       resource:
#         name: memory
#         target:
#           type: Utilization
#           averageUtilization: 80

---
# Optional: NetworkPolicy for Kafka UI (security)
# Uncomment to enable network isolation
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: kafka-ui
#   namespace: kafka-ns
# spec:
#   podSelector:
#     matchLabels:
#       app: kafka-ui
#   policyTypes:
#     - Ingress
#   ingress:
#     - from:
#         - namespaceSelector:
#             matchLabels:
#               name: kafka-ns
#       ports:
#         - protocol: TCP
#           port: 8080