{{- if .Values.kafkaUI.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-ui
{{- end }}
