{{- if .Values.kafkaUI.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-ui
spec:
  type: {{ .Values.kafkaUI.service.type }}
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-ui
  ports:
    - name: http
      port: {{ .Values.kafkaUI.service.port }}
      targetPort: http
      protocol: TCP
      {{- if eq .Values.kafkaUI.service.type "NodePort" }}
      nodePort: null
      {{- end }}
{{- end }}
