{{- if and .Values.kafka.enabled .Values.networkPolicy.enabled }}
{{- $namespace := .Release.Namespace }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kafka.fullname" . }}-kafka-controller
  labels:
    app.kubernetes.io/name: {{ include "kafka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kafka-controller
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    helm.sh/chart: {{ include "kafka.chart" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kafka.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: kafka-controller
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if .Values.networkPolicy.controller.ingress }}
    {{- toYaml .Values.networkPolicy.controller.ingress | nindent 4 }}
    {{- else }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $namespace }}
      ports:
        - protocol: TCP
          port: 9093
    {{- end }}
  egress:
    {{- if .Values.networkPolicy.controller.egress }}
    {{- toYaml .Values.networkPolicy.controller.egress | nindent 4 }}
    {{- else }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $namespace }}
      ports:
        - protocol: TCP
          port: 9092
        - protocol: TCP
          port: 9093
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $namespace }}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kafka.fullname" . }}-kafka-broker
  labels:
    app.kubernetes.io/name: {{ include "kafka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kafka-broker
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    helm.sh/chart: {{ include "kafka.chart" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kafka.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: kafka-broker
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if .Values.networkPolicy.broker.ingress }}
    {{- toYaml .Values.networkPolicy.broker.ingress | nindent 4 }}
    {{- else }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $namespace }}
      ports:
        - protocol: TCP
          port: 9092
    {{- end }}
  egress:
    {{- if .Values.networkPolicy.broker.egress }}
    {{- toYaml .Values.networkPolicy.broker.egress | nindent 4 }}
    {{- else }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $namespace }}
      ports:
        - protocol: TCP
          port: 9092
        - protocol: TCP
          port: 9093
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $namespace }}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- end }}
{{- if .Values.exporters.kafka.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kafka.fullname" . }}-kafka-exporter
  labels:
    app.kubernetes.io/name: {{ include "kafka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kafka-exporter
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    helm.sh/chart: {{ include "kafka.chart" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kafka.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: kafka-exporter
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if .Values.networkPolicy.exporter.ingress }}
    {{- toYaml .Values.networkPolicy.exporter.ingress | nindent 4 }}
    {{- else }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $namespace }}
      ports:
        - protocol: TCP
          port: 9308
    {{- end }}
  egress:
    {{- if .Values.networkPolicy.exporter.egress }}
    {{- toYaml .Values.networkPolicy.exporter.egress | nindent 4 }}
    {{- else }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $namespace }}
      ports:
        - protocol: TCP
          port: 9092
        - protocol: TCP
          port: 9093
        - protocol: TCP
          port: 9308
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $namespace }}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- end }}
{{- end }}
{{- end }}

